spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/clinical_ordering}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:clinical_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:clinical_pass}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.h2.console.enabled=false

